In [1]:
import pandas as pd
import re

In [2]:
reviews = pd.read_csv('Train.csv')

In [3]:
reviews.head()

                                              review label
0  mature intelligent and highly charged melodram...   pos
1  http://video.google.com/videoplay?docid=211772...   pos
2  Title: Opera (1987) Director: Dario Argento Ca...   pos
3  I think a lot of people just wrote this off as...   pos
4  This is a story of two dogs and a cat looking ...   pos

In [4]:
reviews.shape

(40000, 2)

In [5]:
reviews.info

<bound method DataFrame.info of                                                   review label
0      mature intelligent and highly charged melodram...   pos
1      http://video.google.com/videoplay?docid=211772...   pos
2      Title: Opera (1987) Director: Dario Argento Ca...   pos
3      I think a lot of people just wrote this off as...   pos
4      This is a story of two dogs and a cat looking ...   pos
...                                                  ...   ...
39995  There are similarities between Ray Lawrence's ...   neg
39996  For starters, I once met the director when he ...   neg
39997  Much of "Over Her Dead Body" is so painfully u...   neg
39998  "Lifeforce" is a truly bizarre adaptation of t...   pos
39999  I saw this movie at a screener and its the bes...   pos

[40000 rows x 2 columns]>

In [6]:
reviews.label.value_counts()

pos    20011
neg    19989
Name: label, dtype: int64

In [7]:
# Replace pos with 1 and neg with 0
reviews.label.replace('pos',1,inplace=True)
reviews.label.replace('neg',0,inplace = True)

In [8]:
reviews.tail()

                                                  review  label
39995  There are similarities between Ray Lawrence's ...      0
39996  For starters, I once met the director when he ...      0
39997  Much of "Over Her Dead Body" is so painfully u...      0
39998  "Lifeforce" is a truly bizarre adaptation of t...      1
39999  I saw this movie at a screener and its the bes...      1

### Creating NLTK pipeline

In [9]:
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [10]:
tokenizer = RegexpTokenizer(r'\w+') # Select all the words
ps = PorterStemmer()
en_sw = set(stopwords.words('english'))

In [11]:
def getStemmedReview(review):
    #convert all to lower case
    review = review.lower()
    #replace all the br with space
    review = review.replace('<br /><br />',' ')
    #Tokenize 
    #Remove the digit contained word as wwll
    review=re.sub(r"[A-Za-z]+\d+|\d+[A-Za-z]+",'',review).strip()
    tokens = tokenizer.tokenize(review)
    new_tokens = [token for token in tokens if token not in en_sw]
    ste_tokens = [ps.stem(token) for token in new_tokens]
    
    cleaned_review = ' '.join(ste_tokens)
    return cleaned_review

In [12]:
reviews.review = reviews.review.apply(getStemmedReview)

In [13]:
reviews.head(10)

                                              review  label
0  matur intellig highli charg melodrama unbelive...      1
1  http video googl com videoplay docid 211772166...      1
2  titl opera 1987 director dario argento cast cr...      1
3  think lot peopl wrote anoth one tom cruis weir...      1
4  stori two dog cat look way back home old wise ...      1
5  steve carel come first star role 40 year old v...      1
6  go write requir howev summari put top way word...      0
7  ok riski move rent flick thought noth lose wel...      0
8  cannib pair cinemat refer delicatessen plot st...      1
9  one great modern kung fu film lot review seem ...      1

In [14]:
X = reviews.review.values
y = reviews.label.values

### Spliting the datasets into train and test

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
trainx,testx,trainy,testy = train_test_split(X,y,test_size=0.2,random_state=9)
print("Train shapes : X = {}, y = {}".format(trainx.shape,trainy.shape))
print("Test shapes : X = {}, y = {}".format(testx.shape,testy.shape))

Train shapes : X = (32000,), y = (32000,)
Test shapes : X = (8000,), y = (8000,)

In [17]:
def getStemmedFile(inputFile,outputFile):
    output = open(outputFile,'w',encoding='utf-8')
    
    with open(inputFile,encoding='utf-8') as f:
        reviews = f.readlines()
    for review in reviews:
        cleaned_review = getStemmedReview(review)
        print(cleaned_review,file = output)
    output.close()

In [18]:
#cleaned = reviews.review.apply(getStemmedReview)

# Using Sklearn for creating NLP pipeline and implementing naive bayes

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer(ngram_range=(1,2))

In [21]:
X = cv.fit_transform(trainx)

In [22]:
xtest = cv.transform(testx)

In [23]:
X.shape

(32000, 1918308)

In [76]:
cv.get_feature_names()

['00',
 '000',
 '0000000000001',
 '00000001',
 '00001',
 '00015',
 '001',
 '003830',
 '006',
 '007',
 '0079',
 '0080',
 '0083',
 '009',
 '0093638',
 '01',
 '0126',
 '0148',
 '02',
 '020410',
 '0230',
 '03',
 '039',
 '04',
 '044',
 '05',
 '050',
 '06',
 '07',
 '08',
 '089',
 '09',
 '10',
 '100',
 '1000',
 '10000',
 '1000000',
 '10000000000',
 '1001',
 '1004',
 '101',
 '102',
 '103',
 '104',
 '1040',
 '105',
 '1050',
 '106',
 '107',
 '108',
 '109',
 '10_',
 '10â',
 '11',
 '110',
 '1100',
 '111',
 '112',
 '113',
 '1138',
 '115',
 '116',
 '117',
 '118',
 '119',
 '12',
 '120',
 '1200',
 '1201',
 '1202',
 '121',
 '122',
 '123',
 '12383499143743701',
 '124',
 '1242',
 '1249',
 '125',
 '128',
 '129',
 '12â',
 '13',
 '130',
 '1300',
 '131',
 '132',
 '134',
 '135',
 '136',
 '137',
 '138',
 '13848',
 '139',
 '14',
 '140',
 '1408',
 '141',
 '1415',
 '1416',
 '142',
 '1433421',
 '144',
 '1453',
 '1454',
 '146',
 '1479',
 '148',
 '149',
 '1492',
 '14ã',
 '15',
 '150',
 '1500',
 '15000',
 '151',
 '152',
 '155',
 '155âºf',
 '156',
 '1561',
 '157',
 '158',
 '1588',
 '1594',
 '1596',
 '15â',
 '16',
 '160',
 '1600',
 '1602',
 '161',
 '1610',
 '1611',
 '162',
 '1620',
 '1621',
 '163',
 '164',
 '165',
 '166',
 '167',
 '168',
 '169',
 '1690',
 '1692',
 '16ã',
 '17',
 '170',
 '1700',
 '1710',
 '1740',
 '175',
 '1759',
 '177',
 '1775',
 '1776',
 '1780',
 '1790',
 '1792',
 '1793',
 '1794',
 '1798',
 '18',
 '180',
 '1800',
 '1801',
 '1805',
 '1809',
 '181',
 '1812',
 '1816',
 '1817',
 '182',
 '1820',
 '1821',
 '1824',
 '183',
 '1830',
 '1835',
 '1836',
 '1837',
 '1838',
 '1839',
 '1840',
 '1842',
 '1844',
 '1845',
 '1846',
 '1847',
 '185',
 '1850',
 '1852',
 '1853',
 '1854',
 '1855',
 '1857',
 '1858',
 '1859',
 '1860',
 '1861',
 '1862',
 '1863',
 '1864',
 '1865',
 '1866',
 '1868',
 '1869',
 '1870',
 '1871',
 '1872',
 '1873',
 '1874',
 '1876',
 '1879',
 '188',
 '1880',
 '1881',
 '1886',
 '1887',
 '1888',
 '1889',
 '1890',
 '1891',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1897',
 '1898',
 '1899',
 '19',
 '190',
 '1900',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1907â',
 '1908',
 '1909',
 '1910',
 '1910â',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1915â',
 '1916',
 '1917',
 '1918',
 '1919',
 '192',
 '1920',
 '1921',
 '1921â',
 '1922',
 '1923',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1929',
 '1930',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '195',
 '1950',
 '1950â',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1966â',
 '1967',
 '1968',
 '1969',
 '197',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1975â',
 '1976',
 '1977',
 '1978',
 '19784444',
 '1979',
 '19796',
 '198',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '1â',
 '1â½',
 '1ã',
 '20',
 '200',
 '2000',
 '20000',
 '200000',
 '20001',
 '2000â',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '20061114',
 '2007',
 '2007â',
 '2008',
 '20080107',
 '2009',
 '200911290000',
 '201',
 '2010',
 '2011',
 '2012',
 '2013',
 '2015',
 '2017',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2028',
 '2030',
 '2031',
 '2035',
 '2036',
 '2038',
 '2040',
 '2044',
 '2046',
 '2047',
 '2050',
 '2053',
 '2054',
 '2055',
 '206',
 '2060',
 '2069',
 '2070',
 '2080',
 '2084',
 '209',
 '2090',
 '21',
 '210',
 '2100',
 '2112',
 '211772166650071408',
 '2136',
 '215',
 '2151',
 '216',
 '21699',
 '219',
 '22',
 '220',
 '2200',
 '221',
 '2210',
 '22101',
 '222',
 '223',
 '2257',
 '227',
 '229',
 '23',
 '234',
 '2345',
 '2346',
 '237',
 '238',
 '24',
 '240',
 '2400',
 '241',
 '2415',
 '243',
 '248',
 '2480',
 '25',
 '250',
 '2500',
 '2505',
 '2520',
 '2525',
 '25â',
 '26',
 '260',
 '2600',
 '262',
 '2642',
 '265',
 '269',
 '27',
 '270',
 '2700',
 '272',
 '273',
 '274',
 '275',
 '2772',
 '278',
 '28',
 '280',
 '285',
 '29',
 '2â',
 '2â½',
 '30',
 '300',
 '3000',
 '3012',
 '303',
 '305',
 '3064',
 '31',
 '310',
 '315',
 '3199',
 '32',
 '320',
 '3200',
 '327',
 '33',
 '333',
 '34',
 '345',
 '346',
 '3462',
 '347',
 '35',
 '350',
 '3500',
 '351',
 '3516',
 '356',
 '357',
 '35â',
 '36',
 '360',
 '362',
 '367',
 '37',
 '3714',
 '372',
 '373',
 '378',
 '38',
 '3850',
 '39',
 '392',
 '395',
 '39811',
 '39â',
 '3â',
 '40',
 '400',
 '4000',
 '40000',
 '400000',
 '406',
 '409',
 '41',
 '42',
 '420',
 '426',
 '428',
 '43',
 '430',
 '44',
 '440',
 '45',
 '450',
 '4500',
 '451',
 '46',
 '460',
 '465',
 '469',
 '47',
 '475',
 '48',
 '49',
 '498',
 '4â',
 '50',
 '500',
 '5000',
 '502',
 '505',
 '50â',
 '51',
 '52',
 '5200',
 '52000',
 '522',
 '5250',
 '527213',
 '53',
 '54',
 '5400',
 '545',
 '55',
 '5500',
 '5539',
 '555',
 '56',
 '560',
 '566',
 '567',
 '57',
 '571',
 '576',
 '578',
 '58',
 '588',
 '59',
 '5â',
 '60',
 '600',
 '6000',
 '60000',
 '605',
 '607',
 '608',
 '60â',
 '61',
 '610',
 '6100',
 '61514',
 '618',
 '62',
 '620',
 '62229249',
 '63',
 '637',
 '64',
 '65',
 '66',
 '660',
 '666',
 '67',
 '6723',
 '678',
 '68',
 '69',
 '70',
 '700',
 '7000',
 '70000',
 '701',
 '707',
 '70â',
 '70ã',
 '71',
 '713',
 '72',
 '73',
 '7300',
 '735',
 '737',
 '74',
 '747',
 '75',
 '750',
 '757',
 '76',
 '7600',
 '767',
 '77',
 '775',
 '78',
 '788',
 '79',
 '7â',
 '7â½th',
 '80',
 '800',
 '8000',
 '81',
 '810',
 '819',
 '82',
 '820',
 '83',
 '837',
 '84',
 '849',
 '85',
 '850',
 '86',
 '863',
 '87',
 '8700',
 '878',
 '88',
 '886',
 '89',
 '8â½',
 '90',
 '900',
 '9000',
 '900000',
 '90210',
 '905',
 '91',
 '911',
 '914',
 '92',
 '924',
 '93',
 '94',
 '9484',
 '95',
 '96',
 '96â',
 '97',
 '970',
 '978',
 '98',
 '985',
 '987',
 '99',
 '998',
 '999',
 '9999',
 '99â',
 '__',
 '___',
 '____',
 '_____',
 '______',
 '_______',
 '________',
 '_________',
 '____________________________________',
 '______________________________________',
 '________________________________________________________________',
 '__________________________________________________________________',
 '_a',
 '_about_',
 '_absolut',
 '_absurd',
 '_almost_',
 '_am_',
 '_amadeus_',
 '_and_',
 '_angel_',
 '_annie_',
 '_any_',
 '_anyone_',
 '_anything_',
 '_are_',
 '_arlington',
 '_atlanti',
 '_atlantis_',
 '_before_',
 '_boring_',
 '_both_',
 '_bounce_',
 '_brice',
 '_brooklyn_',
 '_can',
 '_cannon_',
 '_cave',
 '_certainly_',
 '_could',
 '_dead_',
 '_di',
 '_dirti',
 '_divinatori',
 '_do_',
 '_dr',
 '_everything_',
 '_exemplarili',
 '_extremeley_',
 '_fantastic_',
 '_film_',
 '_filmic',
 '_forrest',
 '_friend',
 '_glen',
 '_go',
 '_how_',
 '_i_',
 '_innerli',
 '_inspire_',
 '_is_',
 '_looks_',
 '_magic_',
 '_mccarthi',
 '_much_',
 '_my_',
 '_napolean',
 '_new',
 '_not_',
 '_other_',
 '_pay_',
 '_penetrate_',
 '_plan',
 '_possible_',
 '_real_',
 '_really_is_',
 '_shall',
 '_shock',
 '_so_',
 '_some_',
 '_somewhere_',
 '_son',
 '_spinal',
 '_spiritit',
 '_starstruck_',
 '_stranger',
 '_strictli',
 '_that_',
 '_the',
 '_the_lost_empire_',
 '_the_woman_in_white_',
 '_then_',
 '_told_',
 '_toy',
 '_tri',
 '_tuvalu_',
 '_twice',
 '_very_',
 '_want_',
 '_waterdance_',
 '_well_',
 '_whale_',
 '_x',
 'aa',
 'aaa',
 'aaaaaaaaaaaahhhhhhhhhhhhhh',
 'aaaaaaah',
 'aaaaagh',
 'aaaaah',
 'aaaaargh',
 'aaaaarrrrrrgggggghhhhhh',
 'aaaaatch',
 'aaaaaw',
 'aaaahhhhhh',
 'aaaand',
 'aaaawwwwww',
 'aaaggghhhhhhh',
 'aaagh',
 'aaah',
 'aaahhhhhhh',
 'aaargh',
 'aaarrrgh',
 'aaaugh',
 'aab',
 'aachen',
 'aada',
 'aadha',
 'aag',
 'aaghh',
 'aah',
 'aahhh',
 'aaila',
 'aaja',
 'aak',
 'aaker',
 'aakrosh',
 'aaliyah',
 'aalox',
 'aam',
 'aamir',
 'aamr',
 'aamto',
 'aan',
 'aankh',
 'aankhen',
 'aap',
 'aapk',
 'aapkey',
 'aardman',
 'aarf',
 'aargh',
 'aaron',
 'aarp',
 'aarrrgh',
 'aashok',
 'aasman',
 'aatish',
 'aaton',
 'aau',
 'aauugghh',
 'aavjo',
 'aawip',
 'aaww',
 'ab',
 'aba',
 'aback',
 'abadi',
 'abagail',
 'abahi',
 'abanaz',
 'abandon',
 'abank',
 'abash',
 'abashidz',
 'abat',
 'abba',
 'abbad',
 'abbasi',
 'abbey',
 'abbi',
 'abbot',
 'abbott',
 'abbrevi',
 'abbu',
 'abc',
 'abcâ',
 'abd',
 'abdalla',
 'abderrahman',
 'abdic',
 'abdomen',
 'abdomin',
 'abdoo',
 'abduct',
 'abductor',
 'abdul',
 'abdullah',
 'abdulrahman',
 'abe',
 'abecassi',
 'abedalla',
 'abel',
 'abemethi',
 'abercrombi',
 'aberdeen',
 'abernathi',
 'abernethi',
 'aberr',
 'aberystwyth',
 'abet',
 'abey',
 'abgail',
 'abhay',
 'abhi',
 'abhijeet',
 'abhimaan',
 'abhisheh',
 'abhishek',
 'abhor',
 'abhorr',
 'abi',
 'abid',
 'abigail',
 'abigil',
 'abil',
 'abilen',
 'abilityof',
 'abir',
 'abishag',
 'abishai',
 'abishek',
 'abit',
 'abject',
 'abjectli',
 'abkani',
 'abl',
 'ablaz',
 'ablest',
 'abli',
 'abliti',
 'abm',
 'abner',
 'abnorm',
 'abo',
 'aboard',
 'abod',
 'abolish',
 'abolit',
 'abolitionist',
 'abomin',
 'abominationâ',
 'abominib',
 'aborigin',
 'aborigini',
 'aborigon',
 'abort',
 'abortionist',
 'abott',
 'abou',
 'abound',
 'aboutagirli',
 'aboutboul',
 'aboutâ',
 'abov',
 'abr',
 'abra',
 'abraham',
 'abrahm',
 'abram',
 'abrazo',
 'abreast',
 'abridg',
 'abrigado',
 'abril',
 'abroad',
 'abrog',
 'abromowitz',
 'abrupt',
 'abruptli',
 'abscond',
 'abseil',
 'absen',
 'absenc',
 'absencesâ',
 'absent',
 'absentia',
 'absentmind',
 'absentmindedli',
 'absinth',
 'absolout',
 'absoloutley',
 'absolu',
 'absolut',
 'absolutl',
 'absolutley',
 'absolutli',
 'absolv',
 'absorb',
 'absorbingli',
 'absorpt',
 'absoul',
 'absoulutley',
 'absout',
 'absoutley',
 'abstain',
 'abstin',
 'abstract',
 'abstru',
 'absurd',
 'absurdest',
 'absurdist',
 'absurdli',
 ...]

### Implementing Algorithams

In [24]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB,BernoulliNB

In [25]:
mnb = MultinomialNB()
bnb = BernoulliNB()
gnb = GaussianNB()

In [26]:
mnb.fit(X,trainy)

MultinomialNB()

In [27]:
mnb.predict(xtest)

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [28]:
mnb.score(xtest,testy)

0.876375

# 85% accuracy in MNB As we create bigrams our accuracy incr to 88%

In [90]:
bnb.fit(X,trainy)

BernoulliNB()

In [91]:
bnb.score(xtest,testy)

0.840875

# 84% accurcy in BNB

In [113]:
# Due to insuuufficient storage i have to take just 100 thats why accuracy decresses

x = X[:100].toarray()
gnb.fit(x,trainy[:100])

GaussianNB()

In [114]:
gnb.predict(xtest[:100].toarray())

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [115]:
gnb.score(xtest[:100].toarray(),testy[:100])

0.69

### Predicting Test dataset

In [116]:
test = pd.read_csv('Test.csv')

In [117]:
test.head(10)

                                              review
0  Remember those old kung fu movies we used to w...
1  This movie is another one on my List of Movies...
2  How in the world does a thing like this get in...
3  "Queen of the Damned" is one of the best vampi...
4  The Caprica episode (S01E01) is well done as a...
5  I usually really enjoy Steven Seagal movies. T...
6  JiÃ¸Ã­ Trnka made his last animated short an i...
7  This is so bad it will be my contribution to t...
8  Watching this hilariously retro but very enter...
9  Excellent political thriller, played much quie...

In [119]:
test = test.review.apply(getStemmedReview)

In [120]:
testX = test.values

In [121]:
testX = cv.transform(testX)

In [135]:
Y = mnb.predict(testX)

In [138]:
df = pd.DataFrame(test, columns=['review','label'])

In [140]:
df.label = Y

In [141]:
df.head(10)

                                              review  label
0  rememb old kung fu movi use watch friday satur...      0
1  movi anoth one list movi bother saw 40 year ag...      0
2  world thing like get dvd player home even get ...      0
3  queen damn one best vampir movi ever seen movi...      0
4  caprica episod well done pilot realli episod e...      1
5  usual realli enjoy steven seagal movi usual hi...      0
6  jiã ã trnka made last anim short indict totali...      1
7  bad contribut next bad movi parti go clear sta...      0
8  watch hilari retro entertain career girl tale ...      1
9  excel polit thriller play much quieter slower ...      1

In [145]:
df.to_csv('output.csv',index = False)